import type { Metadata } from "next";
import { DM_Sans, Space_Mono } from "next/font/google";
import "./globals.css";
import { VideoProvider } from "@/context/VideoContext";
import { LanguageProvider } from "@/context/LanguageContext";
import { CameraPreview } from "@/components/CameraPreview";

const fontSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = DM_Sans({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = Space_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      >
        <LanguageProvider>
          {/*GLOBAL VIDEO RECORDER CONTEXT */}
          <VideoProvider>
            {children}
            <CameraPreview />
          </VideoProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
